import type { ResidentApplicationData } from '../types/application';

export const todayIso = () => new Date().toISOString().slice(0, 10);

export const initialApplicationData = (): ResidentApplicationData => ({
  personal: {
    legalFirstName: '',
    middleName: '',
    legalLastName: '',
    preferredName: '',
    dateOfBirth: '',
    phone: '',
    email: '',
    currentCity: '',
    currentState: '',
    preferredContactMethod: '',
    preferredMoveInDate: '',
    heardAbout: '',
    referralSource: '',
  },
  readiness: {
    currentLivingSituation: '',
    maintainingSobriety: '',
    sobrietyStartDate: '',
    willingAbstinence: '',
    willingHouseRules: '',
    willingScreening: '',
    participatingProgram: '',
    programName: '',
    programContactName: '',
    programContactInfo: '',
    programPermissionToContact: false,
    legalSupervision: '',
    supervisingAgency: '',
    officerContactName: '',
    officerContactInfo: '',
    legalPermissionToContact: false,
    accessibilityAccommodation: '',
    medicationPolicyDiscussion: '',
  },
  practical: {
    employmentStatus: '',
    incomeSupportSource: '',
    reliableTransportation: '',
    transportationAssistance: '',
    canMeetFinancialRequirements: '',
    emergencyContactName: '',
    emergencyContactRelationship: '',
    emergencyContactPhone: '',
    emergencyContactEmail: '',
    soberLivingGoals: '',
    graceCottageInterest: '',
    additionalInformation: '',
  },
  consent: {
    accurateInfo: false,
    noGuarantee: false,
    mayContact: false,
    agreePolicies: false,
    authorizedContacts: false,
    privacyNotice: false,
    legalSignature: '',
    dateSigned: todayIso(),
    consentToSubmit: false,
  },
  website: '',
});
